USERS_MAP = {
  abeersalameh: { username: 'cwrw', name: 'Abeer Salamah' },
  alessandromencarini: { username: 'amencarini', name: 'Alessandro Mencarini' },
  andy: { username: 'andycroll', name: 'Andy Croll' },
  dcruz: { username: 'dncrht', name: 'Daniel Cruz' },
  emili: { username: 'eparreno', name: 'Emili Parreño' },
  jesper: { username: 'thejspr', name: 'Jesper Kjeldgaard' },
  khietle: { username: 'khiet', name: 'Khiet Le' },
  khoa: { username: 'Karlotcha', name: 'Karlotcha Hoa' },
  kris: { username: 'krisleech', name: '' },
  matt: { username: 'matthutchinson', name: 'Matthew Hutchinson' },
  max: { username: 'MaxKolodziej', name: 'Maksymilian Kołodziej' },
  molawson: { username: 'molawson', name: 'Mo Lawson' },
  motta: { username: 'mottalrd', name: 'Alfredo Motta' },
  mrship: { username: 'mrship', name: 'Andy Shipman' },
  nasir: { username: 'nas', name: 'Nasir Jamal' },
  pedrocunha: { username: 'pedrocunha', name: 'Pedro Cunha' },
  sadamov: { username: 'adamof', name: 'Stefan Adamov' },
  tadej: { username: '', name: 'Tadej' }
}
